### ISSUE TITLE
Bug: Sorting by relation column replaces model original data with relation data

### ISSUE THREAD

**Issue by fahmifitu** [kdion4891/laravel-livewire-tables#11]
Bank:
id
name
country_id

Country:
id
name

Sorting by Country name breaks the data in table and loads data of country into bank columns that has the same name (eg: id, name, created_at, updated_at, etc..)

**Comment by kdion4891** [comment]
have you set up the relationships in the models?

in the column declaration, you'd use something like `country.name`, notice the period. please see the docs.

**Comment by kdion4891** [comment]
You also may need to use `->select('banks.*')` on your query.

**Comment by fahmifitu** [comment]
`->select('banks.*')`

This did the trick! Thanks for the response.
