### ISSUE TITLE
mount method overide 

### ISSUE THREAD

**Issue by on3ss** [kdion4891/laravel-livewire-tables#13]
When overriding the mount method and passing a variable to it.
e.g.

```
//view
@livewire('test-table', ['search' => $search])
//Component
public function mount($search)
    {
        $this->setTableProperties();
        $this->search = $search;
    }
```

This error shows up.
`Declaration of App\Http\Livewire\TestTable::mount($search) should be compatible with Kdion4891\LaravelLivewireTables\TableComponent::mount() (View: F:\PHP Projects\diagnoMarch19\resources\views\result.blade.php)`

**Comment by kdion4891** [comment]
What version of PHP are you running? Also, is this Laravel 7?

I noticed similar problems with Laravel 7 and a PHP version below 7.3. After I set my PHP version to 7.3 these issues went away.

**Comment by on3ss** [comment]
I'm using laravel 6.18 and php 7.2

**Comment by Jean-Da-Rocha** [comment]
@kdion4891 I have the same problem.

```php
public $projectId;

public function mount(Project $project)
{
    $this->setTableProperties();
    $this->projectId = $project->id;
}
```

I'm running Laravel 7, php 7.3 and livewire 1.x

**Comment by oliverbj** [comment]
Same issue for me. It's because in the "original" mount method, there is no argument being passed to it.

How can we solve this?

**Comment by oliverbj** [comment]
So what I did to "solve" this, was to extend the `TableComponent` that all new DataTable classes have. I have created my own "CustomTableComponent" (call it what you want):

This custom component then extends the TableComponent, but in here I can successfully override the `mount()` method, to accept (in my case) an `$id`.

```php
class CustomTableComponent extends TableComponent
{

    public function mount($id = null)
    {
        $this->setTableProperties();
    }

}
```

In my DataTable class, I simply then extend my `CustomTableComponent`:

```php
class UserTable extends CustomTableComponent
{
    public $user_id;
    public function mount($id = null)
    {
        $this->user_id = $id;
        parent::mount($this->user_id);
    }
}
```

**Comment by kdion4891** [comment]
if someone comes up with a decent solution please submit a PR

**Comment by rumeau** [comment]
Hello i've came on this same issue recently.

I'm not sure, but doesn't seems correct to hijack the mount method as is the single method that allows to hook into the mount process.

What i've done was to override the construct and call $this->setTableProperties(); there.

Its wrorking for me and i would be willing to submit a PR but im not sure if it brokes something anywhere else, but as far as I was able to check this method only set some properties based on the configuration file, so it should be a major problem.

Any thoughts?
