### ISSUE TITLE
table is unstyled, could you include a demo please?

### ISSUE THREAD

**Issue by vesper8** [kdion4891/laravel-livewire-tables#2]
It would be very useful if you included a starter-kit or a working demo

right now I was able to install it but the table itself is unstyled.. does it depend on Bootstrap or something else?

**Comment by kdion4891** [comment]
Check the installation in the readme. It works with Laravels built-in UI scaffolding, as well as Font Awesome.

If you don't want to use the Laravel UI scaffolding, you need to install Bootstrap 4 via NPM.
