### ISSUE TITLE
Export to PDF or CSV buttons

### ISSUE THREAD

**Issue by pushpak1300** [kdion4891/laravel-livewire-tables#23]
It will be great if there is button for export to pdf and csv like [datatables](https://datatables.net/extensions/buttons/examples/initialisation/export.html).

**Comment by pushpak1300** [comment]
i don't know we can add that feature using livewire or not .

**Comment by hemant17** [comment]
I also want to do that did you get it ?

**Comment by pushpak1300** [comment]
yes I use [jspdf](https://github.com/MrRio/jsPDF) for exporting pdf and [table2csv](https://github.com/OmbraDiFenice/table2csv) for export csv.
<br>
If you want i can share small snippet with you. @hemant17

**Comment by hemant17** [comment]
it will be greatfull brother if you can share the code it will save my time :)

**Comment by hemant17** [comment]
ok i got it :) still thanks 👍  working fine

**Comment by pushpak1300** [comment]
Okay ! No problem

**Comment by pushpak1300** [comment]
I don't know this repo is actively maintained or not.
I will be adding my Export button code in my repo.
**Check out my [Fork](https://github.com/pushpak1300/laravel-livewire-tables) .**
