### ISSUE TITLE
->hidden() column attribute

### ISSUE THREAD

**Issue by jongravois** [kdion4891/laravel-livewire-tables#3]
One feature that would push a great package "over the top" in my opinion would be the addition of hidden() as a column attribute similar to sortable() and searchable().

For example, Column::make('ID')->searchable()->sortable()->hidden(). This would allow for a column listing to be shown to the user and let them determine what columns are important to see.

Thoughts?

**Comment by kdion4891** [comment]
I'm not sure I understand what you're asking for. You could simply have a cookie, or even a user database column for the ones they want to see, and use `auth()->user()->columns` in the `fields()` declaration or something. I'm still confused with what you're asking tho...

**Comment by jongravois** [comment]
We have a table with 71 columns. 

One department uses only 8 of those columns and another department uses only 12 columns.

For those department users, it would be great if they could pop open a modal and uncheck the columns they don't need to see to get their work done. A hidden() attribute would allow this.

**Comment by kdion4891** [comment]
So then just set your columns based on the department, no?

```
if ($department == 'Department 1') {
    return [
        Column::make()...
    ];
}
else if ($department == 'Department 2') {
    return [
        Column::make()...
    ];
}
```

**Comment by jongravois** [comment]
That actually was my original thought but there is no component, so there is no mount() method to accept anything outside the model unless I missed the boat.

**Comment by kdion4891** [comment]
you don't need to override `mount()`, you can do it inside the `columns()` method.

and even if you do need to override `mount()`, it explains how in the readme:

### `mount()`

This method sets the initial table properties. If you have to override it, be sure to call `$this->setTableProperties()`.

Example:

    public function mount()
    {
        $this->setTableProperties();
        
        // my custom code
    }

**Comment by jongravois** [comment]
You're right.

Sorry I missed that.

Your package is BRILLIANT!!!

**Comment by kdion4891** [comment]
thats what she said
