### ISSUE TITLE
Transform column data from model

### ISSUE THREAD

**Issue by oliverbj** [kdion4891/laravel-livewire-tables#7]
Hi @kdion4891 

Very nice project you have created here! I was wondering, is it possible to transform the data before serving it to the table?

For example, if I have a `name` column, I would like to make sure that the first character is always capitalized:

```php
public function columns()
    {
        return [
            Column::make('Name', 'first_name')->searchable()->sortable(),
        ];
    }
```

How can I do so I can use `ucfirst('first_name')` for example?

**Comment by oliverbj** [comment]
Nevermind, I figured out I could just use the `$this->view()` for this.

**Comment by kdion4891** [comment]
Or use an accessor in your model...
